import api from './axiosInstance';

export const timetableApi = {
  getClasses: () => api.get('/classes'),
  createClass: (data) => api.post('/classes', data),
  updateClass: (id, data) => api.put(`/classes/${id}`, data),
  deleteClass: (id) => api.delete(`/classes/${id}`),
  getCourses: () => api.get('/courses'),
  getCourseById: (id) => api.get(`/courses/${id}`),
  createCourse: (data) => api.post('/courses', data),
  updateCourse: (id, data) => api.put(`/courses/${id}`, data),
  deleteCourse: (id) => api.delete(`/courses/${id}`),
  getFaculty: () => api.get('/faculty'),
  createFaculty: (data) => api.post('/faculty', data),
  updateFaculty: (id, data) => api.put(`/faculty/${id}`, data),
  deleteFaculty: (id) => api.delete(`/faculty/${id}`),
  getRooms: () => api.get('/rooms'),
  createRoom: (data) => api.post('/rooms', data),
  updateRoom: (id, data) => api.put(`/rooms/${id}`, data),
  deleteRoom: (id) => api.delete(`/rooms/${id}`),
  createMetadata: (data) => api.post("/metadata", data),
  getMetadata: () => api.get("/metadata"),
  updateMetadata: (id, data) => api.put(`/metadata/${id}`, data),
  deleteMetadata: (id) => api.delete(`/metadata/${id}`),
  getRooms: () => api.get('/rooms'),
  createRoom: (data) => api.post('/rooms', data),
  updateRoom: (id, data) => api.put(`/rooms/${id}`, data),
  deleteRoom: (id) => api.delete(`/rooms/${id}`),
  generateTimetable: (classId, suggestions) => api.post('/timetable/generate', { classId, suggestions }),
  searchTimetables: (params) => api.get('/timetable', { params }),
  deleteTimetable: (id) => api.delete(`/timetable/${id}`),
};